import { sql } from 'drizzle-orm'
import { bigint, timestamp, uuid } from 'drizzle-orm/pg-core'

// UUIDv7 values are generated by the application, not by a database default.
export function recordId() {
  return uuid('id').primaryKey()
}

export function mutableRecordColumns() {
  return {
    id: recordId(),
    version: bigint('version', { mode: 'bigint' })
      .notNull()
      .default(sql`1`),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  }
}

export function immutableRecordColumns() {
  return {
    id: recordId(),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  }
}
